fullnameOverride: annuums-service
appVersionSuffix: service-chart
namespace: annuums-service

create: false
selector: {}
annotations: {}
ports: []

clusterIP: null
internalTrafficPolicy: null
externalTrafficPolicy: null
sessionAffinity: None
type: ClusterIP
