fullnameOverride: annuums-deployment
appVersionSuffix: deployment-chart
namespace: annuums-deployment

serviceAccount:
  create: false

labels: {}

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

targetGroupBinding: {}

terminationGracePeriodSeconds: 30

autoscaling:
  enabled: false
  hpa: {}
  keda: {}

containers: []

replicas: 1
revisionHistoryLimit: 3

nodeSelector: {}

ports: []

startProbe: {}
readinessProbe: {}
livenessProbe: {}

volumeMounts: []
volumes: []
affinity: {}
tolerations: []
